app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError


class PokeForm(FlaskForm):
    poke_id = StringField('Search for a Pokemon', validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config 
from flask_login import LoginManager #to log users in and out and maintain the session
from flask_sqlalchemy import SQLAlchemy #this talk to the database
from flask_migrate import Migrate #this makes altering the db a lot easier
from flask_moment import Moment




login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'You must be logged in to view this page.'
login.login_message_category = "warning"

db = SQLAlchemy()

migrate = Migrate()
moment = Moment()

def create_app(config_class=Config):

    app = Flask(__name__)
    app.config.from_object(config_class)
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from .blueprints.social import bp as social_bp
    app.register_blueprint(social_bp)
    
    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__, url_prefix='')

from .import routes

app/blueprints/main/routes.py
from flask import render_template, request, redirect, url_for, flash
import requests
from .forms import PokeForm
from app.blueprints.auth.models import Pokemon
from flask_login import login_required, current_user
from sqlalchemy import and_
from .import bp as main



@main.route('/pokeinfo', methods=['GET', 'POST'])
@login_required
def pokeinfo():
    form = PokeForm()
    if request.method == 'POST' and form.validate_on_submit():
        poke = request.form.get('poke_id')
        url = f"https://pokeapi.co/api/v2/pokemon/{poke}"        
        response = requests.get(url)
        if response.ok:            
            data = response.json()            
            poke_dict={
                'poke_name':data['name'],
                'base_hp':data['stats'][0]['base_stat'],
                'base_defense':data['stats'][2]['base_stat'],
                'base_attack':data['stats'][1]['base_stat'],                    
                'front_shiny':data["sprites"]["front_shiny"],
            }            
            flash(f"You found {poke_dict['poke_name']}!", 'success')
            return render_template('pokeinfo.html.j2', poke=poke_dict, form=form)        
        else:
            flash("That's not a Pokemon!", 'danger')
            return render_template('pokeinfo.html.j2', form=form)
    return render_template('pokeinfo.html.j2', form=form)

@main.route('/pokeget/<poke>', methods=['GET', 'POST'])
@login_required
def pokeget(poke):              
    url = f"https://pokeapi.co/api/v2/pokemon/{poke}"        
    response = requests.get(url)                   
    data = response.json()         
    poke_dict={
        'poke_name':data['name'],
        'base_hp':data['stats'][0]['base_stat'],
        'base_defense':data['stats'][2]['base_stat'],
        'base_attack':data['stats'][1]['base_stat'],                    
        'front_shiny':data["sprites"]["front_shiny"],
    }          
    pokemon = Pokemon.query.filter(and_(Pokemon.poke_name==poke, Pokemon.user_id==current_user.id)).all()    
    poke_count = Pokemon.query.filter(Pokemon.user_id==current_user.id).count()
    print(poke_count)
    if pokemon:        
        flash(f"You already caught {poke_dict['poke_name']}!", 'danger')
        return redirect(url_for('main.pokeinfo'))
    elif poke_count >= 5:
        flash("You have the max amount of Pokemon! Please remove some from your roster to add new Pokemon.", 'danger')
        return redirect(url_for('main.pokeinfo'))
    else:
        new_poke=Pokemon(user_id=current_user.id, poke_name=poke_dict['poke_name'], hit_points=poke_dict['base_hp'], defense=poke_dict['base_defense'], attack=poke_dict['base_attack'], poke_img=poke_dict['front_shiny'])
        new_poke.catch()
        flash(f"You caught {poke_dict['poke_name']}!", 'success')        
        return redirect(url_for('main.pokeinfo'))

@main.route('/pokeroster')
@login_required
def pokeroster():
    pokemon= Pokemon.query.all()
    return render_template('pokeroster.html.j2', pokemon = pokemon)

@main.route('/pokerelease/<int:id>')
@login_required
def pokerelease(id):
    poke_to_release = Pokemon.query.get(id)
    poke_to_release.release()
    flash(f"You have released a Pokemon!", 'danger')
    return redirect(url_for('main.pokeinfo'))

@main.route('/pokefight/<int:otherid>')
@login_required
def pokefight(otherid):
    pokemon= Pokemon.query.all()    
    return render_template('pokefight.html.j2', pokemon = pokemon, otherid = otherid)


@main.route('battle/<int:otherid>')
@login_required
def battle(otherid):
    your_attack = 0
    your_defense = 0
    their_attack = 0
    their_defense = 0    
    pokemon= Pokemon.query.all()
    for poke in pokemon:
        if poke.user_id == current_user.id:
            your_defense = your_defense + poke.hit_points + poke.defense
            your_attack = your_attack + poke.attack
        elif poke.user_id == otherid:
            their_defense = their_defense + poke.hit_points + poke.defense
            their_attack = their_attack + poke.attack
    your_score = your_defense - their_attack
    their_score = their_defense - your_attack
    if your_score > their_score:
        flash(f"You win!!! Final score: You = {your_score} | Them = {their_score}", 'success')
        return render_template('pokefight.html.j2', pokemon = pokemon, otherid = otherid)
    elif your_score < their_score:
        flash(f"You lost =( Final score: You = {your_score} | Them = {their_score}", 'danger')
        return render_template('pokefight.html.j2', pokemon = pokemon, otherid = otherid)
    else:
        flash(f"It's a tie! Final score: You = {your_score} | Them = {their_score}", 'warning')
        return render_template('pokefight.html.j2', pokemon = pokemon, otherid = otherid)
    

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='')

from .import routes

app/blueprints/social/routes.py
from .import bp as social
from flask import render_template, flash, redirect, url_for, request
from app.blueprints.auth.models import User, Post
from flask_login import login_required, current_user

@social.route('/', methods = ['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        body=request.form.get('body')
        new_post=Post(user_id=current_user.id, body=body)
        new_post.save()
        return redirect(url_for('social.index'))
    posts=current_user.followed_posts()
    return render_template('index.html.j2', posts=posts)

@social.route('/show_users')
@login_required
def show_users():
    users= User.query.all()
    return render_template('show_users.html.j2', users = users)

@social.route('/follow/<int:id>')
@login_required
def follow(id):
    user_to_follow = User.query.get(id)
    current_user.follow(user_to_follow)
    flash(f"You are now following {user_to_follow.first_name} {user_to_follow.last_name}", 'success')
    return redirect(url_for('social.show_users'))

@social.route('/unfollow/<int:id>')
@login_required
def unfollow(id):
    user_to_unfollow = User.query.get(id)
    current_user.unfollow(user_to_unfollow)
    flash(f"You are no longer friends with {user_to_unfollow.first_name} {user_to_unfollow.last_name}", 'danger')
    return redirect(url_for('social.show_users'))

@social.route('/edit_post/<int:id>', methods=['GET','POST'])
@login_required
def edit_post(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.edit(request.form.get('body'))
        flash("Your post has been edited", 'success')
    return render_template('edit_post.html.j2', post=post)


@social.route('/post/<int:id>')
@login_required
def get_post(id):
    post = Post.query.get(id)
    return render_template('single_post.html.j2', post = post, view_all = True)

@social.route('/post/my_posts')
@login_required
def my_posts():
    posts = current_user.posts
    return render_template('my_posts.html.j2', posts=posts)

app/templates/base.html.j2
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="{{url_for('static',filename='images/favicon.ico')}}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static',filename='images/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='images/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='images/favicon-16x16.png')}}">
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">

    {% block css %}
    {% endblock %}
    
    <title>
        {% block title %}
        Welcome to Pokemon!
        {% endblock %}
    </title> 
  </head>

  <body>
 
  {% include './includes/nav.html.j2' %}

    
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages%}
        {% for class, message in messages %}
        <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
    
    {{ moment.include_moment() }}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

app/templates/edit_post.html.j2
{% extends 'base.html.j2' %}
{% block title %}
Edit Post
{% endblock %}

{% block content %}
<form method="POST" action="{{url_for('social.edit_post', id = post.id)}}">
    <div class='mb-3'>
     <div class="mb-3">
      <textarea class="form-control" p name="body" style="height: 100px;">{{post.body}}</textarea>
    </div>
      <button type="submit" class="btn btn-danger"><i class="fa-solid fa-plane-departure"></i>&nbsp;Submit Edit</button>
</form>

{% endblock %}

app/templates/includes/_post.html.j2
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{post.author.get_icon_url()}}" class="img-fluid rounded-start" alt="avatar">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{post.author.first_name}} {{post.author.last_name}}</h5>
        
        {% if view_all %}
        <p class="card-text">{{post.body}}</p>
        {% else %}
        <p class="card-text">{{post.body | truncate(100)}}</p>
        {% endif %}

        <small><a href="{{url_for('social.get_post', id=post.id)}}">View Post</a></small>

        {% if current_user.id == post.author.id %}
        <small><a href="{{url_for('social.edit_post', id=post.id)}}">Edit Post</a></small>
        {% endif %}

        <p class="card-text"><small class="text-muted">{{moment(post.date_created).fromNow()}} <span style="color:red" class="float-end">{{"edited " + moment(post.date_updated).fromNow() | string() if post.date_updated else ""}}</span></small></p>
        <span style="color:lightcoral" class="float-end">{{"edited "+moment(post.date_updated).fromNow()|string() if post.date_updated else ''}}</span>
      </div>
    </div>
  </div>
</div>

app/templates/includes/nav.html.j2
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('social.index')}}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            
          {% if current_user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{url_for('social.index')}}">Trash Talk</a>
            </li>
            
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.pokeinfo')}}">Pokemon Info</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.pokeroster')}}">Pokemon Roster</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('social.show_users')}}">Other Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
              </li>
            {% endif %}
        </ul>

          {% if current_user.is_authenticated %}
            <ul class="navbar-nav ms-auto">                
              
              
              <a href="{{url_for('social.my_posts')}}">
              <img id="userpic" src="https://avatars.dicebear.com/api/croodles/{{current_user.icon}}.svg" style="height:50px">
              </a>
                <li class="nav-item">
                    <div class="row">
                        <div class="col-12">
                            <a class="nav-link" aria-current="page" href="{{url_for('auth.logout')}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                              <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                            </svg></a>
                        </div>
                        <div class="col-12">
                            <a class="nav-link" aria-current="page" href="{{url_for('auth.edit_profile')}}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                                  </svg>
                            </a>
                        </div>
                    </div>
                </li>


            </ul>
            {% endif %}






        </div>
    </div>
    </nav>

app/templates/index.html.j2
{% extends 'base.html.j2' %}
{% block title %}
  Trash Talk
{% endblock %}

{% block content %}
  
  <form method="POST" action="{{url_for('social.index')}}">
    <div class="mb-3">
      <textarea class="form-control" placeholder="Talk some trash?" name="body" style="height: 100px;"></textarea>
    </div>
      <button type="submit" class="btn btn-primary"><i class="fa-solid fa-plane-departure"></i>&nbsp;Post</button>

  <h1>Pokemon Feed!</h1>
  <hr>
  {% for post in posts %}
    {% include './includes/_post.html.j2' %}
  
  {% endfor %}
  
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}
{% block css %}

<link rel="stylesheet" href="{{url_for('static',filename='login.css')}}">

{% endblock %}

{% block title%}
Poke-Login
{% endblock %}

{% block content %}
<h1>Login</h1>

<form action="{{url_for('auth.login')}}" method="POST">
  {{ form.hidden_tag() }}

  {{ form.email.label(class="form-label") }}
  {{ form.email(class="form-control") }}
  {# email errors #}
  {% for error in form.email.errors %}
   <small style="color:red;">{{ error }}</small><br>
  {% endfor %}
  {# password section #}
  {{ form.password.label(class="form-label") }}
  {{ form.password(class="form-control") }}
  {# submit section #}
  {{ form.submit(class="btn btn-primary") }}
</form>
<small style="color:red;">{{error}}</small>
{% endblock %}

app/templates/my_posts.html.j2
{% extends 'base.html.j2' %}
{% block title %}
Your Junk
{% endblock %}

{% block contecnt %}
    <h1>My Junk</h1>
    <hr>
    {% for post in posts %}
        {% include './includes/_post.html.j2' %}
    {% endfor %}
{% endblock %}

app/templates/pokefight.html.j2
{% extends 'base.html.j2' %}

{% block title %}
Pokemon Fight!
{% endblock %}


{% block content %}
<div class="row">
<div class="col-md-4">
<h1>Your Team:</h1>
{% for poke in pokemon %}

    {% if poke.user_id == current_user.id %}
    <div class="card mb-3" style="max-width: 375px;">
    <div class="row g-0">
            <div class="col-md-4">            
                <img src="{{ poke.get_image_url() }}" class="img-fluid rounded-start" alt="avatar">            
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{poke.poke_name | title}}</h5>
                    <p class="card-text">Hit Points: {{poke.hit_points}}</p>
                    <p class="card-text">Attack Points: {{poke.attack}}</p>
                    <p class="card-text">Defense Points: {{poke.defense}}</p>
                </div>
            </div>
            
    </div>
    </div>
    {% endif %}    
{% endfor %}
</div>
<div class="col-md-4">
    <img src="../static/images/pika_face3.png" class="img-fluid rounded-start" alt="pika">
    <h5>Your attack points will go through their defense and hit points. Then, they will attack you back. The player with the highest hit point/defense score at the end wins!</h5>
    <div class="d-grid gap-2">
        <a href="/battle/{{otherid}}" class="btn btn-danger" type="button">FIGHT?</a>
    </div>
</div>
<div class="col-md-4">
<h1>Their Team:</h1>
{% for poke in pokemon %}
    {% if poke.user_id == otherid %}
    <div class="card mb-3" style="max-width: 375px;">
    <div class="row g-0">
            <div class="col-md-4">            
                <img src="{{ poke.get_image_url() }}" class="img-fluid rounded-start" alt="avatar">            
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{poke.poke_name | title}}</h5>
                    <p class="card-text">Hit Points: {{poke.hit_points}}</p>
                    <p class="card-text">Attack Points: {{poke.attack}}</p>
                    <p class="card-text">Defense Points: {{poke.defense}}</p>
                </div>
            </div>
            
    </div>
    </div>
    {% endif %}
{% endfor %}
</div>
</div>
{% endblock %}

app/templates/pokeinfo.html.j2
{% extends 'base.html.j2' %}

{% block title %}
Pokemon Info
{% endblock %}

{% block content %}
    
    
    
    <h1>Pokemon Info</h1>
    
    
    <form method="POST" action="{{url_for('main.pokeinfo')}}">
    {{ form.hidden_tag() }}
    {{ form.poke_id.label (class = "form-label")}}
    {{ form.poke_id(class = "form-control") }} <br>
    
    {# <div class="mb-3">
        <label for="poke" class="form-label">Pokemon Name</label>
        <input type="text" name="poke" class="form-control" id="poke">
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
    </form> #}
   
   
    {% if poke %}
        <table class="table table-striped table-hover">
        <thead>
            <tr>
            <th scope="col">Pokemon Name</th>
            <th scope="col">HP Base</th>
            <th scope="col">Defense Base</th>
            <th scope="col">Attack Base</th>
            <th scope="col">Image</th>
            
            </tr> 
        </thead>
        <tbody>
            
                <tr>
                    <th scope="row">{{poke['poke_name']|title}}<br><a href="/pokeget/{{poke['poke_name']}}" class="btn btn-danger">Catch 'em!</a></th>
                    
                    <td>{{poke['base_hp']}}</td>
                    <td>{{poke['base_defense']}}</td>
                    <td>{{poke['base_attack']}}</td>    
                    <td><img src="{{poke['front_shiny']}}"></img></td>
                    
                </tr>
            
        </tbody>
        </table>
        
    {% else %}
    Type the Pokemon name you want to know about.
    {% endif %}


{% endblock %}

app/templates/pokeroster.html.j2
{% extends 'base.html.j2' %}

{% block title %}
Pokemon Roster
{% endblock %}


{% block content %}

{% for poke in pokemon %}
    {% if poke.user_id == current_user.id %}
    <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
            <div class="col-md-4">            
                <img src="{{ poke.get_image_url() }}" class="img-fluid rounded-start" alt="avatar">            
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{poke.poke_name | title}}</h5>
                    <p class="card-text">Hit Points: {{poke.hit_points}}</p>
                    <p class="card-text">Attack Points: {{poke.attack}}</p>
                    <p class="card-text">Defense Points: {{poke.defense}}</p>
                </div>
            </div>
            <div class="col-md-2" class="row align-items-center">    
                <a href="/pokerelease/{{poke.id}}" class="btn btn-danger">Remove</a>
            </div>
    </div>
    </div>
    {% endif %}
{% endfor %}


{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}
{% block css %}

<link rel="stylesheet" href="{{url_for('static',filename='login.css')}}">

{% endblock %}
{% block title %}
Register
{% endblock %}
{% block content%}
<h1>Register</h1>

<small style="color:red;">{{error}}</small>
<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.register')}}" method="POST">
{{ form.hidden_tag() }}

 {% if current_user.is_authenticated %}
  <img src="https://avatars.dicebear.com/api/croodles/{{current_user.icon}}.svg" style="height:50px">
  {% endif %}

{{form.icon.label}}<br>
  {% for subfield in form.icon %}
    {{ subfield }}
    {{ subfield.label | safe}}
  {% endfor %}
  <br>
  {% for error in form.icon.errors %}
   <small style="color:red;">{{ error }}</small><br>
  {% endfor %}
  <br>


{{form.first_name.label(class="form-label")}}
{{form.first_name(class="form-control")}}


{{form.last_name.label(class="form-label")}}
{{form.last_name(class="form-control")}}


{{form.email.label(class="form-label")}}
{{form.email(class="form-control")}}


{% for error in form.email.errors %}
    <small style="color:red;">{{error}}</small><br>
{% endfor %}


{{form.password.label(class="form-label")}}
{{form.password(class="form-control")}}


{{form.confirm_password.label(class="form-label")}}
{{form.confirm_password(class="form-control")}}


{% for error in form.password.errors %}
    <small style="color:red;">{{error}}</small><br>
{% endfor %}


{{form.submit(class='btn btn-primary')}}
</form>
{% endblock %}

app/templates/show_users.html.j2
{% extends 'base.html.j2' %}

{% block title %}
All Users
{% endblock %}

{% block content %}

{% for user in users %}
    {% if not user.id == current_user.id %}
    <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
        
        <img src="{{ user.get_icon_url() }}" class="img-fluid rounded-start" alt="avatar">
        
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
            <p class="card-text">Bio coming soon!</p>
            {% if current_user.is_following(user) %}
                <a href="/unfollow/{{user.id}}" class="btn btn-warning">Unfollow</a>
            {% else %}
                <a href="/follow/{{user.id}}" class="btn btn-info">Follow</a>
            {% endif %}
        <a href="/pokefight/{{user.id}}" class="btn btn-danger">Fight!</a>
            

        </div>
        </div>
    </div>
    </div>
    {% endif %}
{% endfor %}


{% endblock %}

app/templates/single_post.html.j2
{% extends 'base.html.j2' %}
{% block title %}
{{post.author.first_name}}'s Post'
{% endblock %}

{% block content %}

{% include 'includes/_post.html.j2' %}

{% endblock %}